services:
  archiq_frontend:
    container_name: archiq_frontend
    command: yarn vite preview --host
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"